server:
  port: 8080

spring:
  application:
    name: ai-gateway
  cloud:
    nacos:
      #服务发现
      discovery:
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        username: ${nacos.username}
        password: ${nacos.password}
        server-addr: ${nacos.server-add}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: business-agent
              uri: lb://business-agent
              predicates:
                - Path=/business/**
            - id: database-agent
              uri: lb://database-agent
              predicates:
                - Path=/database/**
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PWD}
  port: ${REDIS_PORT}

# nacos 账号密码
nacos:
  namespace: agent
  group: ${NACOS_GROUP}
  username: ${NACOS_USERNAME}
  password: ${NACOS_PASSWORD}
  server-add: ${NACOS_SERVER_ADD}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
