server:
  port: 8082
spring:
  profiles:
    active: dev
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
      chat:
        options:
          model: deepseek-v3
    memory:
      redis:
        host: localhost
        port: 6379
        timeout: 5000
        password:
    mcp:
      client:
        request-timeout: 60000
        stdio:
          # 1. 单独放在一个json文件（推荐）
#          servers-configuration: classpath:/mcp/mcp-servers-config.json
          #2. 直接配置全局配置文件中
          connections:
            mysql:
              command: cmd
              args:
                - /c
                - npx
                - -y
                - '@fhuang/mcp-mysql-server'
                - mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/datax

milvus:
  client:
    url: "http://localhost:19530"
    userName: "root"
    password: "milvus"

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

