server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/datax?allowMultiQueries=true&characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedstatements=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
      chat:
        options:
          model: deepseek-v3
    memory:
      redis:
        host: ${redis.host}
        port: ${redis.port}
        timeout: 5000
        password: ${redis.password}
    mcp:
      client:
        request-timeout: 60000
        stdio:
          connections:
            mysql:
              command: npx
              args:
                - -y
                - '@fhuang/mcp-mysql-server'
                - mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/datax
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

auth:
  token-ttl-hours: 2

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PWD}
  port: ${REDIS_PORT}

nacos:
  namespace: agent
  group: ${NACOS_GROUP}
  username: ${NACOS_USERNAME}
  password: ${NACOS_PASSWORD}
  server-add: ${NACOS_SERVER_ADD}

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
